//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public string barkod { get; set; }
        public string ad { get; set; }
        public string toptan { get; set; }
        public string perakende { get; set; }
        public int id { get; set; }
    }
}
